baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[build]
  writeStats = true

[params]
    title = "LGC Personal Page"
    author = "Luiz Gabriel Correia"
    description = "Luiz G. Correia Personal Page"
    #copyright = "Copyleft"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "ocean"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Luiz Gabriel Correia"
        tagline = "Master's Student"
        location = "Santo André, SP"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/luigcorreia/"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-stack-overflow"
            url = "https://stackoverflow.com/users/7124764/luiz-g-correia"
            title = "StackOverflow"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/luizgcorreia"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/luigcorreia"
            title = "Twitter"
        [[params.social.list]]
            icon = "fab fa-orcid"
            url = "https://orcid.org/0000-0002-2721-4274"
            title = "Orcid"
        #[[params.social.list]]
        #    icon = "ai ai-google-scholar"
        #    url = "#"
        #    title = "Google Scholar"
        [[params.social.list]]
            icon = "fab fa-researchgate"
            url = "https://www.researchgate.net/profile/Luiz-Correia"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "Master's Student in Computer Science at UFABC, Santo André, Brazil. Research in Science of Science, Bibliometrics, Agent-based Modelling, AI and Machine Learning."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "IT Consultant"
            dates = "2019 - 2020"
            company = "NELIE - Núcleo de Empreendedorismo e Liberdade Econômica"
            details = "Fiz parte como como consultor de TI do corpo administrativo do Núcleo de Empreendedorismo da UFABC, entidade estudantil dedicada a promover uma postura empreendedora no ambiente universitário."
        [[params.experience.list]]
            position = "IT Consultant"
            dates = "2018 - 2019"
            company = "LegalBot"
            details = "Consultoria de TI em um projeto de Data Science aplicado à compliance em ambiente corporativo, com dedecção automatizada de potenciais conflitos de interesse."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "M.S. in Computer Science"
            college = "Federal University of ABC"
            dates = "2021 - On going"
        [[params.education.list]]
            degree = "B.S. in Computer Science"
            college = "Federal University of ABC"
            dates = "2017 - 2020"
            thesis_title = "Number X - Um Framework Web para simulações interativas de física e matemática."
            thesis_url = "https://drive.google.com/file/d/1pG1a3TrseKzEWni-lZGcanHNX7RnrjFW/view?usp=share_link"
        [[params.education.list]]
            degree = "B.S. in Science and Technology"
            college = "Federal University of ABC"
            dates = "2014 - 2018"
            thesis_title = "Escalabilidade e possíveis soluções para redes blockchain."

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Coming soon"]

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Agent-based model for simulating the evolution of Science"
            url = "#"
            description = "Projeto desenvolvido em Netlogo com objetivo de estudar como medidas bibliométricas e políticas editoriais afetam a evolução das publicações acadêmicas e a capacidade de resolução de problemas das ciência."
        [[params.project.list]]
            title = "Number X"
            url = "https://drive.google.com/file/d/1pG1a3TrseKzEWni-lZGcanHNX7RnrjFW/view?usp=share_link"
            description = "Jogo educacional baseado em um motor 3D para simulações de física e matemática."

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Python, Pandas"
            skillrating = 80
        [[params.skill.list]]
            skill = "Netlogo, ABM"
            skillrating = 80
        [[params.skill.list]]
            skill = "Linux"
            skillrating = 70
        [[params.skill.list]]
            skill = "JavaScript"
            skillrating = 70
        [[params.skill.list]]
            skill = "Java"
            skillrating = 70
        [[params.skill.list]]
            skill = "C/C++"
            skillrating = 60

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Gaming"
        [[params.hobby.list]]
            hobby = "Anime"
        [[params.hobby.list]]
            hobby = "DIY Projects"
        [[params.hobby.list]]
            hobby = "Hiking/Camping"
        [[params.hobby.list]]
            hobby = "Baking"
        
